char *create_array(unsigned int size, char c);
char *_strdup(char *str);
char *str_concat(char *s1, char *s2);
int **alloc_grid(int width, int height);
void free_grid(int **grid, int height);
char *argstostr(int ac, char **av);
int _putchar(char c);
char *_concat(char *concatenate, char *s1, char *s2);
int _strlen(char *str);
int findlength(int ac, char **av);
char *writeconcat(char *concatstr, int ac, char **av);
char **strtow(char *str);
int wordcount(char *str);
int lettercount(int i, char *str);
int fillarray(int i, char *str, char *array);
